# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  pd-contract-test-producer:
    build:
      target: development
    image: pd-contract-test-producer-development
    container_name: pd-contract-test-producer-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

networks:
  pd-contract-test-producer:
    name: pd-contract-test-producer
    driver: bridge
