services:
  pd-contract-test-producer:
    build:
      context: .
      target: production
    image: pd-contract-test-producer
    container_name: pd-contract-test-producer
    environment:
      APPINSIGHTS_CLOUDROLE: pd-contract-test-producer-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      SESSION_PASSWORD: this-is-not-a-real-password-just-for-local-testing
